name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace '3.x' with the specific Python version you need, e.g., '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt  # Ensure your repo has a `requirements.txt` file for dependencies

    - name: Run tests
      run: |
        pytest --maxfail=5 --disable-warnings  # Modify pytest arguments as needed

    - name: Upload test results (optional)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ./.pytest_cache